// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TaskFlowPro.API.Data;

#nullable disable

namespace TaskFlowPro.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260708092521_AddColorHexToTasks")]
    partial class AddColorHexToTasks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("RoleId")
                        .HasColumnType("text");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("UsageType")
                        .HasColumnType("integer");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoList", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ColorHex")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<bool>("IsCollaborative")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<int>("ListType")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid?>("WorkoutTemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.HasIndex("WorkoutTemplateId");

                    b.ToTable("TodoLists");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoSubtask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TaskId");

                    b.ToTable("TodoSubtasks");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AssigneeId")
                        .HasColumnType("text");

                    b.Property<string>("ColorHex")
                        .HasColumnType("text");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsImportant")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Priority")
                        .HasColumnType("integer");

                    b.Property<int>("SortIndex")
                        .HasColumnType("integer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int?>("TimePerformanceMinutes")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("WorkStartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("TodoTasks");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.UserListPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FilterJson")
                        .HasColumnType("text");

                    b.Property<int>("GroupBy")
                        .HasColumnType("integer");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortBy")
                        .HasColumnType("integer");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ViewType")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("UserListPreferences");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.UserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("text");

                    b.Property<string>("GoogleCalendarToken")
                        .HasColumnType("text");

                    b.Property<bool>("IsGoogleConnected")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsOutlookConnected")
                        .HasColumnType("boolean");

                    b.Property<string>("OutlookCalendarToken")
                        .HasColumnType("text");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("UserProfiles");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("MetricLabel1")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MetricLabel2")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId");

                    b.ToTable("WorkoutExercises");

                    b.HasData(
                        new
                        {
                            Id = new Guid("28682a0e-94ec-4ca4-86a0-ea0409a805c8"),
                            Category = "Chest",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Bench Press",
                            SortOrder = 1,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("7b5394be-b333-4074-be46-4cb0a4c0bf49"),
                            Category = "Chest",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Incline Press",
                            SortOrder = 2,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("b8719bc4-3b2d-4db7-a4b7-5a1bf2f4e3c3"),
                            Category = "Chest",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Decline Press",
                            SortOrder = 3,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("70f5e7f1-bc8e-49b0-9515-566b6070a2a4"),
                            Category = "Chest",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Chest Dips",
                            SortOrder = 4,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("9876251b-5e92-4fcf-840f-7b70bc92b0c1"),
                            Category = "Back",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Lat Pulldown (Vertical Pull)",
                            SortOrder = 5,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("2269a9ff-05de-4d57-b08e-7e9bfa3d88b4"),
                            Category = "Back",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Cable Rows (Horizontal Pull)",
                            SortOrder = 6,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("785d06d4-8d48-43d9-a78b-d7b3ea0a8e0f"),
                            Category = "Back",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Deadlift",
                            SortOrder = 7,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("8c3b28b6-9df2-466d-a36c-94116c4f0b2f"),
                            Category = "Legs",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Barbell Squats",
                            SortOrder = 8,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("f5c0b021-f3b1-4f9e-a8bf-1049969d30fe"),
                            Category = "Legs",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Leg Press",
                            SortOrder = 9,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        },
                        new
                        {
                            Id = new Guid("e3d06eb4-3e9a-4ad3-9b88-1c49603099bc"),
                            Category = "Legs",
                            MetricLabel1 = "Weight (kg)",
                            MetricLabel2 = "Reps",
                            Name = "Leg Curls",
                            SortOrder = 10,
                            TemplateId = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc")
                        });
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutLoggedExercise", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciseId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciseId");

                    b.HasIndex("SessionId");

                    b.ToTable("WorkoutLoggedExercises");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<double>("TotalVolume")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("ListId");

                    b.ToTable("WorkoutSessions");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutSetLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("LoggedExerciseId")
                        .HasColumnType("uuid");

                    b.Property<double>("Reps")
                        .HasColumnType("double precision");

                    b.Property<int>("SetIndex")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("LoggedExerciseId");

                    b.ToTable("WorkoutSetLogs");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("WorkoutTemplates");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c3a647db-d8fc-4235-824f-ef7ebf836dfc"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Description = "Track sets, reps, and calculate total lifting volume for Chest, Back, and Legs.",
                            Icon = "Dumbbell",
                            Name = "Gym Workout Tracker"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlowPro.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoList", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.AppUser", "Owner")
                        .WithMany("Lists")
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TaskFlowPro.API.Models.WorkoutTemplate", "WorkoutTemplate")
                        .WithMany()
                        .HasForeignKey("WorkoutTemplateId");

                    b.Navigation("Owner");

                    b.Navigation("WorkoutTemplate");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoSubtask", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.TodoTask", "Task")
                        .WithMany("SubTasks")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Task");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoTask", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.TodoList", "List")
                        .WithMany("Tasks")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.UserProfile", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.AppUser", "User")
                        .WithOne("Profile")
                        .HasForeignKey("TaskFlowPro.API.Models.UserProfile", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutExercise", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.WorkoutTemplate", "Template")
                        .WithMany("Exercises")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Template");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutLoggedExercise", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.WorkoutExercise", "Exercise")
                        .WithMany()
                        .HasForeignKey("ExerciseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TaskFlowPro.API.Models.WorkoutSession", "Session")
                        .WithMany("LoggedExercises")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercise");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutSession", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.TodoList", "List")
                        .WithMany("WorkoutSessions")
                        .HasForeignKey("ListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("List");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutSetLog", b =>
                {
                    b.HasOne("TaskFlowPro.API.Models.WorkoutLoggedExercise", "LoggedExercise")
                        .WithMany("SetLogs")
                        .HasForeignKey("LoggedExerciseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoggedExercise");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.AppUser", b =>
                {
                    b.Navigation("Lists");

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoList", b =>
                {
                    b.Navigation("Tasks");

                    b.Navigation("WorkoutSessions");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.TodoTask", b =>
                {
                    b.Navigation("SubTasks");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutLoggedExercise", b =>
                {
                    b.Navigation("SetLogs");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutSession", b =>
                {
                    b.Navigation("LoggedExercises");
                });

            modelBuilder.Entity("TaskFlowPro.API.Models.WorkoutTemplate", b =>
                {
                    b.Navigation("Exercises");
                });
#pragma warning restore 612, 618
        }
    }
}
